// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7DO-cJJ1VfNFX-TZxPl_BvetHjtP1VE',
    appId: '1:797180658052:web:5e73218cfbf2f810271dd1',
    messagingSenderId: '797180658052',
    projectId: 'my-quiz-poroject',
    authDomain: 'my-quiz-poroject.firebaseapp.com',
    storageBucket: 'my-quiz-poroject.appspot.com',
    measurementId: 'G-2DMYJHJNBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtGcgeI-nWSUkBZNP5bQ9fiVpJgbQ1gxM',
    appId: '1:797180658052:android:6118e33ece8a7548271dd1',
    messagingSenderId: '797180658052',
    projectId: 'my-quiz-poroject',
    storageBucket: 'my-quiz-poroject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHRkmS1Hm1nSEWdJBk29PHDky6cHy4cY',
    appId: '1:797180658052:ios:701a251120bc96d3271dd1',
    messagingSenderId: '797180658052',
    projectId: 'my-quiz-poroject',
    storageBucket: 'my-quiz-poroject.appspot.com',
    iosClientId: '797180658052-0b54mcd98pj828reblse07e30l18ilt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myQuizProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHRkmS1Hm1nSEWdJBk29PHDky6cHy4cY',
    appId: '1:797180658052:ios:701a251120bc96d3271dd1',
    messagingSenderId: '797180658052',
    projectId: 'my-quiz-poroject',
    storageBucket: 'my-quiz-poroject.appspot.com',
    iosClientId: '797180658052-0b54mcd98pj828reblse07e30l18ilt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myQuizProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7DO-cJJ1VfNFX-TZxPl_BvetHjtP1VE',
    appId: '1:797180658052:web:30a8b2db5c59f886271dd1',
    messagingSenderId: '797180658052',
    projectId: 'my-quiz-poroject',
    authDomain: 'my-quiz-poroject.firebaseapp.com',
    storageBucket: 'my-quiz-poroject.appspot.com',
    measurementId: 'G-DCTLRXN698',
  );
}
